export const COMMISSION_HISTORY = [
    {
        sid: "1",
        email: "analyst.rick@gmail.com",
        restaurant_id: "REST0007",
        restaurant_name: "Elephant & Castle",
        amount: "150.00",
        order_amt: "150.00",
        discount: "5.00",
        commission: "15.00",
        add_on_amt: "6.00",
        add_on_commission: "0.60",
        cancel: "0.00",
        transaction_id: "1234",
        balance: "135.40",
        paid_amt: "0",
        due_amt:"135.40",
        paid: false,
        paid_date: "",
    },
]
export const TRANSACTION_HISTORY = [
    {
        sid: "1",
        email: "analyst.rick@gmail.com",
        restaurant_id: "REST0007",
        transaction_id:"null",
        restaurant_name: "Elephant & Castle",
        amount: "150.00",
        deposited_on: "null",
        start_date: "01-May-2022",
        end_date:"15-May-2022",
        order_amt: "150.00",
        discount: "5.00",
        commission: "15.00",
        add_on_amt: "6.00",
        add_on_commission: "0.60",
        balance: "135.40",
        paid_amt: "0",
        paid: false,
        paid_date: "",
    },
]