export const COMMISSION_HISTORY=[
    {
        sid:"1",
        email: "sumitranjan245@gmail.com",
        restaurant_id: "REST001",
        restaurant_name: "DRAGON HOUSE",
        amount: "$100.00",
        commission: "$15.00",
        cancel:"$0.00",
        transaction_id: "",
        paid: "",
        paid_date: "",
    },
    {
        sid:"2",
        email: "sumitranjan245@gmail.com",
        restaurant_id: "REST002",
        restaurant_name: "World Best Foods",
        amount: "$300.00",
        commission: "$45.00",
        cancel:"$0.00",
        transaction_id: "",
        paid: "",
        paid_date: "",
    },
    {
        sid:"3",
        email: "sumitranjan245@gmail.com",
        restaurant_id: "REST001",
        restaurant_name: "DRAGON HOUSE",
        amount: "$100.00",
        commission: "$15.00",
        cancel:"$0.00",
        transaction_id: "",
        paid: "",
        paid_date: "",
    }
]